# Generated by Django 4.2.7 on 2026-02-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_analysisrequest_total_influence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalartifact',
            name='video',
            field=models.URLField(blank=True, help_text='URL-адрес видео артефакта', max_length=500, null=True, verbose_name='Видео'),
        ),
    ]
