# Generated by Django 4.2.7 on 2025-11-06 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='total_influence_score',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Суммарный показатель влияния всех артефактов', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общий показатель влияния'),
        ),
    ]
