# Generated by Django 4.2.7 on 2025-11-13 05:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название культурного артефакта', max_length=200, verbose_name='Название')),
                ('author', models.CharField(help_text='Автор или создатель артефакта', max_length=100, verbose_name='Автор')),
                ('description', models.TextField(help_text='Подробное описание культурного артефакта', verbose_name='Описание')),
                ('publication_year', models.CharField(help_text='Год первой публикации или создания', max_length=4, verbose_name='Год публикации')),
                ('genre', models.CharField(choices=[('POST_APOCALYPTIC', 'Постапокалиптическая фантастика'), ('SCIENCE_FICTION', 'Научная фантастика'), ('FANTASY', 'Фэнтези'), ('CLASSIC', 'Классика'), ('MODERN', 'Современная литература'), ('HISTORICAL', 'Исторический роман'), ('DETECTIVE', 'Детектив'), ('ROMANCE', 'Роман'), ('OTHER', 'Другое')], help_text='Жанровая принадлежность', max_length=50, verbose_name='Жанр')),
                ('base_influence_score', models.IntegerField(help_text='Базовый показатель культурного влияния', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базовый показатель влияния')),
                ('citation_count', models.IntegerField(help_text='Количество академических и научных цитирований', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество цитирований')),
                ('media_mentions', models.IntegerField(help_text='Количество упоминаний в средствах массовой информации', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Упоминания в СМИ')),
                ('social_media_score', models.IntegerField(help_text='Популярность в социальных сетях (0-1000)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Показатель социальных сетей')),
                ('adaptation_count', models.IntegerField(help_text='Количество экранизаций и адаптаций', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество адаптаций')),
                ('image', models.URLField(blank=True, help_text='URL-адрес изображения артефакта', max_length=500, null=True, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли артефакт в системе', verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Культурный артефакт',
                'verbose_name_plural': 'Культурные артефакты',
                'ordering': ['-base_influence_score', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено'), ('DELETED', 'Удален')], default='DRAFT', help_text='Текущий статус анализа', max_length=20, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('research_title', models.CharField(help_text='Название аналитического исследования', max_length=300, verbose_name='Название исследования')),
                ('researcher_name', models.CharField(help_text='ФИО исследователя или руководителя проекта', max_length=100, verbose_name='Имя исследователя')),
                ('research_scope', models.CharField(choices=[('GLOBAL', 'глобальный'), ('REGIONAL', 'региональный'), ('NATIONAL', 'национальный'), ('LOCAL', 'локальный')], help_text='Географический или тематический масштаб исследования', max_length=20, verbose_name='Масштаб исследования')),
                ('methodology', models.CharField(choices=[('CITATION_ANALYSIS', 'комплексный анализ цитирований'), ('CONTENT_ANALYSIS', 'контент-анализ'), ('DISCOURSE_ANALYSIS', 'дискурс-анализ'), ('STATISTICAL_ANALYSIS', 'статистический анализ'), ('COMPARATIVE_ANALYSIS', 'сравнительный анализ'), ('MIXED_METHODS', 'смешанные методы')], help_text='Используемая методология исследования', max_length=50, verbose_name='Методология')),
                ('total_influence_score', models.DecimalField(decimal_places=2, default=1, help_text='Суммарный показатель влияния всех артефактов', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общий показатель влияния')),
                ('description', models.TextField(blank=True, help_text='Подробное описание целей и задач исследования', null=True, verbose_name='Описание исследования')),
                ('completion_date', models.DateTimeField(blank=True, help_text='Дата завершения анализа', null=True, verbose_name='Дата завершения')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли запрос анализа', verbose_name='Активный')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос анализа',
                'verbose_name_plural': 'Запросы анализа',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Вес артефакта в анализе (от 0 до 1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Вес')),
                ('analysis_depth', models.CharField(choices=[('BASIC', 'базовая'), ('EXTENDED', 'расширенный'), ('COMPREHENSIVE', 'комплексный')], help_text='Уровень детализации анализа для данного артефакта', max_length=20, verbose_name='Глубина анализа')),
                ('calculated_score', models.DecimalField(blank=True, decimal_places=2, help_text='Расчетный показатель влияния с учетом веса', max_digits=10, null=True, verbose_name='Расчетный показатель')),
                ('analysis_request', models.ForeignKey(help_text='Родительский запрос анализа', on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='app.analysisrequest', verbose_name='Запрос анализа')),
                ('cultural_artifact', models.ForeignKey(help_text='Связанный культурный артефакт', on_delete=django.db.models.deletion.CASCADE, to='app.culturalartifact', verbose_name='Культурный артефакт')),
            ],
            options={
                'verbose_name': 'м-м Артефакт анализа',
                'verbose_name_plural': 'м-м Артефакты анализа',
                'ordering': ['-weight'],
                'unique_together': {('analysis_request', 'cultural_artifact')},
            },
        ),
    ]
